import { jsPDF } from "jspdf";
import type { BrandAnalysis } from "./analyzeBrand";
import { contrastTextColor, parseCssColor } from "./colorUtils";
import { rasterizeToPng } from "./imageUtils";
import type { BrandIntake } from "./types";

function rgbTuple(hex: string): [number, number, number] {
  const rgb = parseCssColor(hex) ?? { r: 0, g: 0, b: 0 };
  return [rgb.r, rgb.g, rgb.b];
}

function bytesToDataUrl(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return `data:image/png;base64,${btoa(binary)}`;
}

/**
 * Builds a one-page brand guidelines PDF (Pro) — colours, fonts, logo, and
 * contact details in a single shareable, print-ready document. Ships
 * alongside the free Word (.docx) brand guidelines, which stays the
 * editable copy.
 */
export async function buildBrandGuidelinesPdf(
  intake: BrandIntake,
  analysis: BrandAnalysis,
  conceptName: string,
  name: string,
): Promise<Blob> {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  // Header band
  doc.setFillColor(...rgbTuple(analysis.primaryColor));
  doc.rect(0, 0, pageWidth, 120, "F");

  if (intake.logo) {
    try {
      const { bytes, width, height } = await rasterizeToPng(intake.logo.dataUrl, 300);
      const h = 56;
      const w = (width / height) * h;
      doc.addImage(bytesToDataUrl(bytes), "PNG", margin, 32, w, h);
    } catch {
      // Logo failed to rasterize — header band still renders without it.
    }
  }

  const onPrimary = contrastTextColor(parseCssColor(analysis.primaryColor) ?? { r: 0, g: 0, b: 0 });
  doc.setTextColor(...rgbTuple(onPrimary));
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(`${name} — Brand Guidelines`, pageWidth - margin, 55, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Direction: ${conceptName}`, pageWidth - margin, 75, { align: "right" });

  y = 160;
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Colours", margin, y);
  y += 24;

  const swatches: Array<[string, string]> = [
    ["Primary", analysis.primaryColor],
    ["Secondary", analysis.secondaryColor],
    ["Accent", analysis.accentColor],
    ["Background", analysis.backgroundColor],
  ];
  const swatchSize = 44;
  const gap = 24;
  swatches.forEach(([label, hexColor], i) => {
    const x = margin + i * (swatchSize + gap);
    doc.setFillColor(...rgbTuple(hexColor));
    doc.roundedRect(x, y, swatchSize, swatchSize, 6, 6, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    doc.text(label, x, y + swatchSize + 14);
    doc.text(hexColor.toUpperCase(), x, y + swatchSize + 26);
  });

  y += swatchSize + 56;
  doc.setDrawColor(230, 230, 230);
  doc.line(margin, y, pageWidth - margin, y);
  y += 32;

  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Typography", margin, y);
  y += 26;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(`Heading font:  ${analysis.headingFont}`, margin, y);
  y += 18;
  doc.text(`Body font:  ${analysis.bodyFont}`, margin, y);
  y += 40;

  doc.setDrawColor(230, 230, 230);
  doc.line(margin, y, pageWidth - margin, y);
  y += 32;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Tone", margin, y);
  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const toneLines = doc.splitTextToSize(analysis.toneSummary, pageWidth - margin * 2);
  doc.text(toneLines, margin, y);
  y += toneLines.length * 14 + 10;
  if (analysis.styleTags.length) {
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(analysis.styleTags.join("   •   "), margin, y);
    y += 30;
  }

  doc.setDrawColor(230, 230, 230);
  doc.line(margin, y, pageWidth - margin, y);
  y += 32;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text("Contact", margin, y);
  y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  [intake.business.address, intake.business.phone, intake.business.email, intake.business.websiteUrl]
    .filter(Boolean)
    .forEach((line) => {
      doc.text(line, margin, y);
      y += 16;
    });

  doc.setFontSize(8);
  doc.setTextColor(170, 170, 170);
  doc.text("Generated by BrandPunk", margin, doc.internal.pageSize.getHeight() - 24);

  return doc.output("blob");
}
