import { toBlob } from "html-to-image";
import JSZip from "jszip";
import { saveAs } from "file-saver";
import type { BrandAnalysis } from "./analyzeBrand";
import { buildBrandGuidelinesDocx, buildLetterheadDocx } from "./exportDocx";
import { buildEmailSignatureHtml } from "./exportEmailSignature";
import { buildInvoiceXlsx } from "./exportXlsx";
import type { BrandIntake } from "./types";

async function captureNodePng(node: HTMLElement): Promise<Blob> {
  const blob = await toBlob(node, { pixelRatio: 3, cacheBust: true });
  if (!blob) throw new Error("Could not render image");
  return blob;
}

export type PackNodes = {
  businessCard: HTMLElement;
  letterhead: HTMLElement;
  socialPost: HTMLElement;
};

export async function downloadBrandPack({
  intake,
  analysis,
  conceptName,
  name,
  nodes,
}: {
  intake: BrandIntake;
  analysis: BrandAnalysis;
  conceptName: string;
  name: string;
  nodes: PackNodes;
}): Promise<void> {
  const zip = new JSZip();
  const slug = name.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "brandpunk";

  const [cardPng, letterheadPng, socialPng, letterheadDocx, invoiceXlsx, guidelinesDocx] = await Promise.all([
    captureNodePng(nodes.businessCard),
    captureNodePng(nodes.letterhead),
    captureNodePng(nodes.socialPost),
    buildLetterheadDocx(intake, analysis, name),
    buildInvoiceXlsx(intake, analysis, name),
    buildBrandGuidelinesDocx(intake, analysis, conceptName, name),
  ]);

  zip.folder("Business Cards")?.file(`${slug}-business-card.png`, cardPng);
  zip.folder("Letterheads")?.file(`${slug}-letterhead.png`, letterheadPng);
  zip.folder("Letterheads")?.file(`${slug}-letterhead.docx`, letterheadDocx);
  zip.folder("Social Media")?.file(`${slug}-instagram-post.png`, socialPng);
  zip.folder("Sales")?.file(`${slug}-invoice-template.xlsx`, invoiceXlsx);
  zip.folder("Digital")?.file(`${slug}-email-signature.html`, buildEmailSignatureHtml(intake, analysis, name));
  zip.folder("Brand")?.file(`${slug}-brand-guidelines.docx`, guidelinesDocx);

  const readme = `${name} — Brand Pack (${conceptName})
Generated by BrandPunk

/Business Cards   — print-ready PNG
/Letterheads      — PNG + an editable Word (.docx) template
/Social Media     — Instagram-ready PNG
/Sales            — editable Excel (.xlsx) invoice template
/Digital          — HTML email signature (paste into your email client's signature settings)
/Brand            — a short Word (.docx) brand guidelines summary

Colours: ${analysis.primaryColor}, ${analysis.secondaryColor}, ${analysis.accentColor}
Heading font: ${analysis.headingFont}
Body font: ${analysis.bodyFont}
`;
  zip.file("README.txt", readme);

  const zipBlob = await zip.generateAsync({ type: "blob" });
  saveAs(zipBlob, `${slug}-brand-pack.zip`);
}
